FROM node:latest

ENV PORT 3000

# Create app directory
RUN mkdir -p /client
WORKDIR /client

# Installing dependencies
COPY package*.json /client
RUN npm install

# Copying source files
COPY . /client

# Building app
RUN npm run build
EXPOSE 3000

# Running the app
CMD "npm" "run" "dev"