import Head from 'next/head'
import VideoBox from '../components/VideoBox'

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src='/main.js'></script>
      </Head>
      <VideoBox />
    </>
  )
}