import Head from 'next/head'
import { useRef, useState } from 'react'
import useCamera from '../hooks/useCamera'

const maxVideoSize = 200

export default function Home() {
  const [processing, updateProcessing] = useState(false)
  const videoElement = useRef(null)
  const canvasEl = useRef(null)
  useCamera(videoElement, maxVideoSize);

  async function onClick() {
    updateProcessing(true)

    const ctx = canvasEl.current.getContext('2d')
    ctx.drawImage(videoElement.current, 0, 0, maxVideoSize, maxVideoSize)
    const image = ctx.getImageData(0, 0, maxVideoSize, maxVideoSize)

    Module._sum(12324);

    const processedImage = image
    ctx.putImageData(processedImage, 0, 0)
    updateProcessing(false)
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src='/wasm.js'></script>
      </Head>
      <div
        style={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          flexDirection: 'column',
        }}
      >
        <video className="video" playsInline ref={videoElement} />
        <button
          disabled={processing}
          style={{ width: maxVideoSize, padding: 10 }}
          onClick={onClick}
        >
          {processing ? 'Processing...' : 'Take a photo'}
        </button>
        <canvas
          ref={canvasEl}
          width={maxVideoSize}
          height={maxVideoSize}
        ></canvas>
      </div>
    </>
  )
}